import Head from "next/head";
import styles from "../../styles/Home.module.css";
// antd
import { Row, Col } from "antd";
// comp
import Layout from "../components/Layout";
// widget
import Card from "../widgets/Card";

export default function Home(data: any) {
  const list = data.data;
  return (
    <>
      <Head>
        <title>Nextjs Polls API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Row gutter={[16, 16]}>
            {list.map((item: any,index: number) => (
              <Col span={12} key={index}>
                <Card card={item} />
              </Col>
            ))}
          </Row>
        </main>
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://polls.apiblueprint.org/questions");
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
